In [1]:
import numpy as np
import pandas as pd
# from multiprocessing.dummy import Pool as ThreadPool
from multiprocessing import Pool, cpu_count, freeze_support
from functools import partial
from scipy.stats import multivariate_normal
from timeit import timeit

In [2]:
def mvn_loglik(param):
    out = (multivariate_normal.logpdf(p[0], p[1], p[2]) for i, p in enumerate(param))
    return out

In [3]:
def mvn_loglik_helper(p):
    out = multivariate_normal.logpdf(p[0], p[1], p[2])
    return out

In [1]:
def mvn_loglik_par(param):
    n = max(1, cpu_count() - 1)
    pool = ThreadPool(n)
    results = pool.map(mvn_loglik_helper, param)
    pool.close()
    pool.join()
    return results

In [5]:
n = 100000
data = np.zeros([n,2])
mu = np.zeros([n,2])
cov = np.tile(np.eye(2,2), (n,1,1))

In [15]:
param = list(zip(*[data, mu, cov]))
assert np.all(mvn_loglik(param) == mvn_loglik_par(param))

AssertionError: 

In [6]:
def f():
    param = list(zip(*[data, mu, cov]))
    return list(mvn_loglik(param))

In [7]:
def g():
    param = list(zip(*[data, mu, cov]))
    return mvn_loglik_par(param)

In [8]:
print(timeit(f, number=1))

8.3676819


In [10]:
print(timeit(g, number=1))

10.187561600000002


In [2]:
def batch(seq, size):
  return [
    seq[i:i + size]
    for i in range(0, len(seq), size)
  ]

In [15]:
len(param) / processes

12500.0

In [20]:
# batch(param, np.int(len(param) / processes))

In [ ]:
n = 100000
data = np.zeros([n,2])
mu = np.zeros([n,2])
cov = np.tile(np.eye(2,2), (n,1,1))

def batch(seq, size):
  return [
    seq[i:i + size]
    for i in range(0, len(seq), size)
  ]

processes = cpu_count()
print(f'Using {processes} processes')

param = list(zip(*[data, mu, cov]))
# chunks = np.array_split(param, processes)
chunks = batch(param, np.int(len(param) / processes))
# Map the labels across the processes
with Pool(processes=processes) as pool:
    result = pool.map(partial(mvn_loglik, param=param), chunks)

Using 8 processes


In [4]:
np.array_split(np.array(param), processes)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


ValueError: could not broadcast input array from shape (2,2) into shape (2)

In [7]:
np.array_split(np.array([1,2,3,4,5,6,7,8,9]), processes)

[array([1, 2]),
 array([3]),
 array([4]),
 array([5]),
 array([6]),
 array([7]),
 array([8]),
 array([9])]

In [11]:
np.array(param[1], dtype=object).shape

ValueError: could not broadcast input array from shape (2,2) into shape (2)

In [1]:
1+1

2

In [29]:
150000 * 112 * 315 * 4 /(1024**3)

19.71423625946045

In [14]:
import numpy as np
np.getsizeof(1)

AttributeError: module 'numpy' has no attribute 'getsizeof'

In [27]:
np.ones(1).astype(np.float32).itemsize

4